-- USERS 테이블 생성

CREATE TABLE `USER` (
     `USER_ID` INT AUTO_INCREMENT NOT NULL,
     `NAME` VARCHAR(10) NOT NULL,
     `EMAIL` VARCHAR(40) NOT NULL,
     `CREATED_DATE` DATETIME NOT NULL,
     `MOD_DATE` DATETIME NOT NULL,
     PRIMARY KEY (`USER_ID`)
);

-- SCHEDULES 테이블 생성

CREATE TABLE `SCHEDULE` (
    `SCHEDULE_ID` INT AUTO_INCREMENT NOT NULL,
    `TITLE` VARCHAR(20) NOT NULL,
    `CONTENTS` VARCHAR(200) NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `MOD_DATE` DATETIME NOT NULL,
    `USER_ID` INT NOT NULL,
    PRIMARY KEY (`SCHEDULE_ID`),
    INDEX (`USER_ID`),
    CONSTRAINT `FK_SCHEDULES_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`)
);

-- COMMENT 테이블 생성

CREATE TABLE COMMENT (
     `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
     `CONTENTS` VARCHAR(200) NOT NULL,
     `CREATED_DATE` DATETIME NOT NULL,
     `MOD_DATE` DATETIME NOT NULL,
     `SCHEDULE_ID` INT,
     `USER_ID` INT,
     PRIMARY KEY (`COMMENT_ID`),
     FOREIGN KEY (`SCHEDULE_ID`) REFERENCES SCHEDULE(`SCHEDULE_ID`),
     FOREIGN KEY (`USER_ID`) REFERENCES USER(`USER_ID`)
);