-- USERS 테이블 생성

CREATE TABLE `USERS` (
     `USER_ID` INT AUTO_INCREMENT NOT NULL,
     `NAME` VARCHAR(10) NOT NULL,
     `EMAIL` VARCHAR(40) NOT NULL,
     `CREATED_DATE` DATETIME NOT NULL,
     `MOD_DATE` DATETIME NOT NULL,
     PRIMARY KEY (`USER_ID`)
);

-- SCHEDULES 테이블 생성

CREATE TABLE `SCHEDULES` (
    `SCHEDULE_ID` INT AUTO_INCREMENT NOT NULL,
    `TITLE` VARCHAR(20) NOT NULL,
    `CONTENTS` VARCHAR(200) NOT NULL,
    `CREATED_DATE` DATETIME NOT NULL,
    `MOD_DATE` DATETIME NOT NULL,
    `USER_ID` INT NOT NULL,
    PRIMARY KEY (`SCHEDULE_ID`),
    INDEX (`USER_ID`),
    CONSTRAINT `FK_SCHEDULES_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`) -- USERS 테이블의 USER_ID를 SCHEDULES 테이블의 FK로 설정
);


-- 일정 생성
INSERT INTO scheduler.SCHEDULES (SCHEDULE_ID, TITLE, CONTENTS, CREATED_DATE, MOD_DATE, USER_ID) VALUES
    (1, '쇼핑', '쇼핑목록 : 컴퓨터, 모니터', NOW(), NOW(), 1)

-- 전체 일정 조회
SELECT *
FROM SCHEDULES
ORDER BY MOD_DATE DESC

-- 선택 일정 조회
SELECT *
FROM SCHEDULES
WHERE SCHEDULE_ID = 1

-- 선택한 일정 수정
UPDATE SCHEDULES
SET TITLE = "밥 먹기"
where SCHEDULE_ID = 1

-- 선택한 일정 삭제
DELETE FROM SCHEDULES
WHERE SCHEDULE_id = 1


-- 유저 생성

-- 유저 전체 조회

-- 유저 선택 조회

-- 유저 삭제